### ISSUE TITLE
OPTIONS for user: limits of points & doubles

### ISSUE THREAD

**Issue by NumyaOrion** [recke96/HemaTournament#43]
For every tournament the user can enter the amount of points necessary to end a fight 
e.g. 7 points --> as soon as a fencer exceeds 7 points in a fight, the fight ends and the fencer with the higher score gets a win/ draw if equal score ecc.

The user also enters the amount of double hits that cause the end of a fight (see issue "We hate double hits")

**Comment by recke96** [comment]
How should this feature look like. 
Is this just general information in the tournament?

Basic score entry is already done (incl. double hit, with a rework planned for #28.)

**Comment by recke96** [comment]
We just won't implement upper limits for points
